---
title: "Where are Torontonians likely to get married"
subtitle: "Analysing the different marriage offices around GTA"
author: 
  - Aamishi Avarsekar
thanks: "Code and data are available at: https://github.com/aamishi/marriages_weekly_reflection/tree/master"
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
# bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(dplyr)
library(arrow)
library(knitr)

data <- read_parquet("../data/analysis_data/analysis_data.parquet")
```


# Introduction

In this week's reflection exercise, I will take a look at where people from GTA are most likely to register their marriage. I will be using @citeR to simulate, test and analyse this data. I will download the data from @opendatatoronto.



# Data 

### point 1: general table to show a glimpse of the data
```{r}
#| label: fig-general-data-todo
#| fig-cap: General table TODO
#| echo: false

kable(data, caption = "Table: Sample Measurements of Subjects")
```

Talk more about it.


```{r}

```

Talk way more about it. 



\newpage


# References


